version: '3'
services:

  mongodb:
    image: mongo:4
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=biconfig
    volumes:
      - egg-mongo:/data/db
      - ./init.d/mongo:/docker-entrypoint-initdb.d
    networks:
      - docker_biconfig
    ports:
      - 27017:27017

volumes:
  egg-mongo:

networks:
  docker_biconfig:
    driver: bridge